#!/bin/bash
# Fix Auto-restart for Clawdbot Remote Node
# Configures LaunchAgent on remote Mac for automatic startup

set -e

echo "🔧 Clawdbot Auto-restart Fix"
echo "============================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REMOTE_HOST="192.168.1.245"
REMOTE_USER="tywhitaker"
GATEWAY_HOST="Mac.local"
GATEWAY_IP="192.168.1.230"
GATEWAY_PORT="18789"

# Functions
print_step() {
    echo -e "${BLUE}➤${NC} $1"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check prerequisites
check_prereqs() {
    print_step "Checking prerequisites..."

    # Test SSH connection
    if ! ssh -o ConnectTimeout=5 -o BatchMode=yes ${REMOTE_USER}@${REMOTE_HOST} "echo test" &>/dev/null; then
        print_error "Cannot SSH to ${REMOTE_USER}@${REMOTE_HOST}"
        echo "    Please ensure:"
        echo "    1. Remote Mac is powered on"
        echo "    2. SSH key is configured"
        echo "    3. Network is reachable"
        exit 1
    fi

    print_success "SSH connection verified"

    # Check if clawdbot is installed on remote
    if ! ssh ${REMOTE_USER}@${REMOTE_HOST} 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && command -v clawdbot' &>/dev/null; then
        print_error "Clawdbot not found on remote Mac"
        echo "    Please install: npm install -g clawdbot@latest"
        exit 1
    fi

    print_success "Clawdbot installed on remote"
    echo ""
}

# Create startup script on remote
create_startup_script() {
    print_step "Creating startup script on remote Mac..."

    ssh ${REMOTE_USER}@${REMOTE_HOST} << 'ENDSSH'
mkdir -p ~/.clawdbot/scripts
mkdir -p ~/.clawdbot/logs

cat > ~/.clawdbot/scripts/start-node.sh << 'EOF'
#!/bin/bash
# Clawdbot Node Startup Script
# Auto-generated by fix-auto-restart.sh

LOG_FILE="$HOME/.clawdbot/logs/startup.log"
mkdir -p "$(dirname "$LOG_FILE")"

# Redirect all output to log
exec >> "$LOG_FILE" 2>&1

echo "=========================================="
echo "Clawdbot Node Startup - $(date)"
echo "=========================================="

# Load nvm
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    echo "Loading nvm from $NVM_DIR/nvm.sh"
    . "$NVM_DIR/nvm.sh"
else
    echo "ERROR: nvm not found at $NVM_DIR/nvm.sh"
    exit 1
fi

# Display versions
echo "Node version: $(node --version 2>/dev/null || echo 'not found')"
echo "NPM version: $(npm --version 2>/dev/null || echo 'not found')"

# Verify clawdbot is available
if ! command -v clawdbot &> /dev/null; then
    echo "ERROR: clawdbot command not found"
    echo "PATH: $PATH"
    exit 1
fi

echo "Clawdbot version: $(clawdbot --version 2>/dev/null || echo 'unknown')"

# Wait for network to be available
echo ""
echo "Waiting for network initialization..."
sleep 10

# Test gateway connectivity with retries
GATEWAY_URL="192.168.1.230"
GATEWAY_PORT="18789"
MAX_ATTEMPTS=30

echo "Testing gateway connectivity to $GATEWAY_URL:$GATEWAY_PORT..."
for i in $(seq 1 $MAX_ATTEMPTS); do
    if curl -s --connect-timeout 2 "http://$GATEWAY_URL:$GATEWAY_PORT/health" > /dev/null 2>&1; then
        echo "✓ Gateway reachable on attempt $i"
        break
    fi
    if [ $i -eq $MAX_ATTEMPTS ]; then
        echo "WARNING: Gateway not reachable after $MAX_ATTEMPTS attempts"
        echo "Starting node anyway - will retry connection internally"
    else
        echo "Attempt $i/$MAX_ATTEMPTS: Gateway not reachable, waiting 2s..."
        sleep 2
    fi
done

# Start the Clawdbot node
echo ""
echo "Starting Clawdbot node..."
clawdbot node start --host Mac.local --port 18789

# Log completion
echo ""
echo "Startup script completed at $(date)"
echo "=========================================="
EOF

chmod +x ~/.clawdbot/scripts/start-node.sh
echo "✓ Startup script created"
ENDSSH

    print_success "Startup script created"
}

# Create LaunchAgent plist
create_launch_agent() {
    print_step "Creating LaunchAgent on remote Mac..."

    ssh ${REMOTE_USER}@${REMOTE_HOST} << 'ENDSSH'
cat > ~/Library/LaunchAgents/com.clawdbot.node.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.clawdbot.node</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>$HOME/.clawdbot/scripts/start-node.sh</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>30</integer>

    <key>StandardOutPath</key>
    <string>/Users/tywhitaker/.clawdbot/logs/launchd-stdout.log</string>

    <key>StandardErrorPath</key>
    <string>/Users/tywhitaker/.clawdbot/logs/launchd-stderr.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>/Users/tywhitaker</string>
    </dict>

    <key>WorkingDirectory</key>
    <string>/Users/tywhitaker</string>
</dict>
</plist>
EOF

# Verify plist syntax
if plutil -lint ~/Library/LaunchAgents/com.clawdbot.node.plist > /dev/null 2>&1; then
    echo "✓ LaunchAgent plist created and validated"
else
    echo "ERROR: Invalid plist syntax"
    exit 1
fi
ENDSSH

    print_success "LaunchAgent created"
}

# Load the LaunchAgent
load_launch_agent() {
    print_step "Loading LaunchAgent..."

    ssh ${REMOTE_USER}@${REMOTE_HOST} << 'ENDSSH'
# Unload existing agent if present
launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist 2>/dev/null || true

# Small delay
sleep 1

# Load the agent
launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist

# Verify it's loaded
if launchctl list | grep -q "com.clawdbot.node"; then
    echo "✓ LaunchAgent loaded successfully"
else
    echo "ERROR: LaunchAgent failed to load"
    exit 1
fi
ENDSSH

    print_success "LaunchAgent loaded"
}

# Verify setup
verify_setup() {
    print_step "Verifying setup..."
    echo ""

    # Check LaunchAgent status
    echo "LaunchAgent status:"
    ssh ${REMOTE_USER}@${REMOTE_HOST} 'launchctl list | grep clawdbot || echo "  (not found)"'
    echo ""

    # Wait for node to start
    echo "Waiting for node to start (15 seconds)..."
    sleep 15

    # Check node status
    echo ""
    echo "Node status:"
    ssh ${REMOTE_USER}@${REMOTE_HOST} 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && clawdbot node status 2>/dev/null || echo "  Node not responding"'
    echo ""

    # Check startup log
    echo "Recent startup log:"
    ssh ${REMOTE_USER}@${REMOTE_HOST} 'tail -10 ~/.clawdbot/logs/startup.log 2>/dev/null || echo "  (no log yet)"'
    echo ""
}

# Display summary
show_summary() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_success "Auto-restart Configuration Complete!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📁 Files created on remote Mac:"
    echo "   ~/.clawdbot/scripts/start-node.sh"
    echo "   ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   ~/.clawdbot/logs/ (log directory)"
    echo ""
    echo "🔧 Management commands (run on remote Mac):"
    echo "   Start:   launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Stop:    launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Status:  launchctl list | grep clawdbot"
    echo "   Logs:    tail -f ~/.clawdbot/logs/startup.log"
    echo ""
    echo "🧪 Test with reboot:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'sudo reboot'"
    echo "   # Wait 2-3 minutes, then check:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'clawdbot node status'"
    echo ""
    echo "📚 Documentation:"
    echo "   See: docs/AUTO_RESTART_FIX.md"
    echo ""
}

# Main execution
main() {
    echo "This script will configure auto-restart for the Clawdbot node"
    echo "on remote Mac: ${REMOTE_USER}@${REMOTE_HOST}"
    echo ""

    check_prereqs
    create_startup_script
    create_launch_agent
    load_launch_agent
    verify_setup
    show_summary
}

# Handle arguments
case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [--verify-only]"
        echo ""
        echo "Configures auto-restart for Clawdbot node on remote Mac."
        echo ""
        echo "Options:"
        echo "  --verify-only   Only check current status, don't make changes"
        echo "  --help, -h      Show this help message"
        exit 0
        ;;
    --verify-only)
        check_prereqs
        verify_setup
        exit 0
        ;;
    *)
        main
        ;;
esac
