#!/bin/bash
# Fix Auto-restart for Clawdbot Remote Node
# Configures LaunchAgent on remote Mac for automatic startup

set -e

# shellcheck source=lib/common.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

echo "🔧 Clawdbot Auto-restart Fix"
echo "============================"
echo ""

# Load configuration
load_env

# Configuration from environment (no hardcoded values)
: "${REMOTE_HOST:?Set REMOTE_HOST in .env or environment}"
: "${REMOTE_USER:?Set REMOTE_USER in .env or environment}"
: "${GATEWAY_HOST:?Set GATEWAY_HOST in .env or environment}"
: "${GATEWAY_IP:?Set GATEWAY_IP in .env or environment}"
: "${GATEWAY_PORT:=18789}"

# Check prerequisites
check_prereqs() {
    print_step "Checking prerequisites..."

    # Test SSH connection
    if ! ssh_check "${REMOTE_USER}@${REMOTE_HOST}"; then
        print_error "Cannot SSH to ${REMOTE_USER}@${REMOTE_HOST}"
        echo "    Please ensure:"
        echo "    1. Remote Mac is powered on"
        echo "    2. SSH key is configured"
        echo "    3. Network is reachable"
        exit 1
    fi

    print_success "SSH connection verified"

    # Check if clawdbot is installed on remote
    if ! ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && command -v clawdbot' &>/dev/null; then
        print_error "Clawdbot not found on remote Mac"
        echo "    Please install: npm install -g clawdbot@latest"
        exit 1
    fi

    print_success "Clawdbot installed on remote"
    echo ""
}

# Create startup script and LaunchAgent on remote (combined for performance)
setup_remote() {
    print_step "Setting up auto-restart on remote Mac..."

    # Get remote user's home directory and username
    local remote_home remote_username
    remote_home=$(ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'echo $HOME')
    remote_username=$(ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" 'whoami')

    # Pass all configuration as environment variables to remote
    # shellcheck disable=SC2087
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" \
        "GATEWAY_IP='${GATEWAY_IP}' GATEWAY_PORT='${GATEWAY_PORT}' GATEWAY_HOST='${GATEWAY_HOST}' REMOTE_HOME='${remote_home}' REMOTE_USER='${remote_username}'" \
        bash << 'ENDSSH'
set -e

# Create directories
mkdir -p ~/.clawdbot/scripts
mkdir -p ~/.clawdbot/logs

echo "Creating startup script..."

# Create startup script (uses environment variables passed from host)
cat > ~/.clawdbot/scripts/start-node.sh << EOF
#!/bin/bash
# Clawdbot Node Startup Script
# Auto-generated by fix-auto-restart.sh

LOG_FILE="\$HOME/.clawdbot/logs/startup.log"
mkdir -p "\$(dirname "\$LOG_FILE")"

# Redirect all output to log
exec >> "\$LOG_FILE" 2>&1

echo "=========================================="
echo "Clawdbot Node Startup - \$(date)"
echo "=========================================="

# Load nvm
export NVM_DIR="\$HOME/.nvm"
if [ -s "\$NVM_DIR/nvm.sh" ]; then
    echo "Loading nvm from \$NVM_DIR/nvm.sh"
    . "\$NVM_DIR/nvm.sh"
else
    echo "ERROR: nvm not found at \$NVM_DIR/nvm.sh"
    exit 1
fi

# Display versions
echo "Node version: \$(node --version 2>/dev/null || echo 'not found')"
echo "NPM version: \$(npm --version 2>/dev/null || echo 'not found')"

# Verify clawdbot is available
if ! command -v clawdbot &> /dev/null; then
    echo "ERROR: clawdbot command not found"
    echo "PATH: \$PATH"
    exit 1
fi

echo "Clawdbot version: \$(clawdbot --version 2>/dev/null || echo 'unknown')"

# Wait for network to be available
echo ""
echo "Waiting for network initialization..."
sleep 10

# Test gateway connectivity with exponential backoff
GATEWAY_URL="${GATEWAY_IP}"
GATEWAY_PORT="${GATEWAY_PORT}"
MAX_ATTEMPTS=30
DELAY=2

echo "Testing gateway connectivity to \$GATEWAY_URL:\$GATEWAY_PORT..."
for i in \$(seq 1 \$MAX_ATTEMPTS); do
    if curl -s --connect-timeout 2 "http://\$GATEWAY_URL:\$GATEWAY_PORT/health" > /dev/null 2>&1; then
        echo "✓ Gateway reachable on attempt \$i"
        break
    fi
    if [ \$i -eq \$MAX_ATTEMPTS ]; then
        echo "WARNING: Gateway not reachable after \$MAX_ATTEMPTS attempts"
        echo "Starting node anyway - will retry connection internally"
    else
        echo "Attempt \$i/\$MAX_ATTEMPTS: Gateway not reachable, waiting \${DELAY}s..."
        sleep \$DELAY
        # Exponential backoff (cap at 30s)
        DELAY=\$((DELAY < 30 ? DELAY * 2 : 30))
    fi
done

# Start the Clawdbot node
echo ""
echo "Starting Clawdbot node..."
clawdbot node start --host ${GATEWAY_HOST} --port ${GATEWAY_PORT}

# Log completion
echo ""
echo "Startup script completed at \$(date)"
echo "=========================================="
EOF

chmod +x ~/.clawdbot/scripts/start-node.sh
echo "✓ Startup script created"

echo ""
echo "Creating LaunchAgent..."

# Create LaunchAgent plist (uses $HOME for portability)
cat > ~/Library/LaunchAgents/com.clawdbot.node.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.clawdbot.node</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>-c</string>
        <string>\$HOME/.clawdbot/scripts/start-node.sh</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>30</integer>

    <key>StandardOutPath</key>
    <string>${REMOTE_HOME}/.clawdbot/logs/launchd-stdout.log</string>

    <key>StandardErrorPath</key>
    <string>${REMOTE_HOME}/.clawdbot/logs/launchd-stderr.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        <key>HOME</key>
        <string>${REMOTE_HOME}</string>
    </dict>

    <key>WorkingDirectory</key>
    <string>${REMOTE_HOME}</string>
</dict>
</plist>
EOF

# Verify plist syntax
if plutil -lint ~/Library/LaunchAgents/com.clawdbot.node.plist > /dev/null 2>&1; then
    echo "✓ LaunchAgent plist created and validated"
else
    echo "ERROR: Invalid plist syntax"
    exit 1
fi

echo ""
echo "Loading LaunchAgent..."

# Unload existing agent if present
launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist 2>/dev/null || true

# Small delay
sleep 1

# Load the agent
launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist

# Verify it's loaded
if launchctl list | grep -q "com.clawdbot.node"; then
    echo "✓ LaunchAgent loaded successfully"
else
    echo "ERROR: LaunchAgent failed to load"
    exit 1
fi
ENDSSH

    print_success "Remote setup complete"
}

# Verify setup
verify_setup() {
    print_step "Verifying setup..."
    echo ""

    # Batch all verification in single SSH call
    ssh_cmd "${REMOTE_USER}@${REMOTE_HOST}" << 'ENDSSH'
echo "LaunchAgent status:"
launchctl list | grep clawdbot || echo "  (not found)"
echo ""

echo "Waiting for node to start (15 seconds)..."
sleep 15

echo ""
echo "Node status:"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
clawdbot node status 2>/dev/null || echo "  Node not responding"

echo ""
echo "Recent startup log:"
tail -10 ~/.clawdbot/logs/startup.log 2>/dev/null || echo "  (no log yet)"
ENDSSH

    echo ""
}

# Display summary
show_summary() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_success "Auto-restart Configuration Complete!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📁 Files created on remote Mac:"
    echo "   ~/.clawdbot/scripts/start-node.sh"
    echo "   ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   ~/.clawdbot/logs/ (log directory)"
    echo ""
    echo "🔧 Management commands (run on remote Mac):"
    echo "   Start:   launchctl load ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Stop:    launchctl unload ~/Library/LaunchAgents/com.clawdbot.node.plist"
    echo "   Status:  launchctl list | grep clawdbot"
    echo "   Logs:    tail -f ~/.clawdbot/logs/startup.log"
    echo ""
    echo "🧪 Test with reboot:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'sudo reboot'"
    echo "   # Wait 2-3 minutes, then check:"
    echo "   ssh ${REMOTE_USER}@${REMOTE_HOST} 'clawdbot node status'"
    echo ""
    echo "📚 Documentation:"
    echo "   See: docs/AUTO_RESTART_FIX.md"
    echo ""
}

# Show help
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Configures auto-restart for Clawdbot node on remote Mac."
    echo ""
    echo "Options:"
    echo "  --verify-only   Only check current status, don't make changes"
    echo "  --help, -h      Show this help message"
    echo ""
    echo "Required environment variables (set in .env):"
    echo "  REMOTE_HOST     IP address of remote Mac"
    echo "  REMOTE_USER     Username on remote Mac"
    echo "  GATEWAY_HOST    Hostname of gateway (e.g., Mac.local)"
    echo "  GATEWAY_IP      IP address of gateway"
    echo ""
    echo "Optional:"
    echo "  GATEWAY_PORT    Gateway port (default: 18789)"
    echo ""
    exit 0
}

# Main execution
main() {
    echo "This script will configure auto-restart for the Clawdbot node"
    echo "on remote Mac: ${REMOTE_USER}@${REMOTE_HOST}"
    echo ""

    check_prereqs
    setup_remote
    verify_setup
    show_summary
}

# Handle arguments
case "${1:-}" in
    --help|-h)
        show_help
        ;;
    --verify-only)
        check_prereqs
        verify_setup
        exit 0
        ;;
    *)
        main
        ;;
esac
